### PR TITLE
DOC-5958 Java DCP Client (unsupported)

### PR DESCRIPTION
**Pull request by RichardSmedley**
Explicit mention, so that search produces a result on this.

### CODE REVIEW

**Review by ingenthr — CHANGES_REQUESTED** [review]
I can't quite tell where this ends up in the documentation.  Can you clarify?

I did a search to find the section, but failed:
https://www.google.com/search?q=%22lowest+latency%22+site%3Adocs.couchbase.com%2Fserver%2F6.5%2Fintroduction%2F&oq=%22lowest+latency%22+site%3Adocs.couchbase.com%2Fserver%2F6.5%2Fintroduction%2F&aqs=chrome..69i57.10846j0j4&sourceid=chrome&ie=UTF-8

**Comment by RichardSmedley** [comment]
https://docs.couchbase.com/java-sdk/3.0/concept-docs/data-services.html#lowest-latency
(seems a good page to target developers likely to consider using it)

**Comment by osfameron** [comment]
@ingenthr @RichardSmedley is this change still needed?
I don't see it on the URL linked above.

If needed, I will close this PR and apply to 7.0 branch.

**Comment by RichardSmedley** [comment]
> @ingenthr @RichardSmedley is this change still needed?
> I don't see it on the URL linked above.

This is a PM (and Support) call - DCP client is unsupported
...but some customers do use it, as it's the lowest latency, especially if they don't want to mess around with Spark.

The question is, do we point to it here, saying this is useful information,
or do we hide it away and pretend it's not there.
I know what I'd prefer ;)

**Comment by osfameron** [comment]
Did somebody say something? 🙉 
While Richard is on *cough* holiday, I'll add this to our Docs Sync meeting agenda today 😄

**Comment by osfameron** [comment]
Agreed with MI and AV to close this pull.

**Pull request closed without merging**
